USE [master]
GO

/****** Object:  Database [offlinepocdb]    Script Date: 10/12/2018 3:34:11 PM ******/
CREATE DATABASE [offlinepocdb]
GO

ALTER DATABASE [offlinepocdb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [offlinepocdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [offlinepocdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [offlinepocdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [offlinepocdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [offlinepocdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [offlinepocdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [offlinepocdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [offlinepocdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [offlinepocdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [offlinepocdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [offlinepocdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [offlinepocdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [offlinepocdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [offlinepocdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [offlinepocdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [offlinepocdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [offlinepocdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [offlinepocdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [offlinepocdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [offlinepocdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [offlinepocdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [offlinepocdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [offlinepocdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [offlinepocdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [offlinepocdb] SET  MULTI_USER 
GO

ALTER DATABASE [offlinepocdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [offlinepocdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [offlinepocdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [offlinepocdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [offlinepocdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [offlinepocdb] SET QUERY_STORE = OFF
GO

USE [offlinepocdb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [offlinepocdb] SET  READ_WRITE 
GO

